"""Render a markdown dashboard of project-wide AI attribution.

Output is a single .md file with native GitHub-rendered Mermaid charts and
tables. Designed to be auto-committed to the repo on every push to main,
giving teams a private, free, always-up-to-date project view.
"""
from __future__ import annotations

from collections import Counter, defaultdict
from datetime import datetime, timezone
from pathlib import Path

from ai_pr_attribution.events import read_chunks
from ai_pr_attribution.schema import AiCodeChunk

TOOL_LABELS = {"claude_code": "Claude Code", "cursor": "Cursor", "codex": "Codex"}
DASHBOARD_MARKER = "<!-- ai-pr-attribution:dashboard -->"


def render_dashboard_markdown(events_file: Path) -> str:
    chunks = read_chunks(events_file)
    if not chunks:
        return _empty()

    total_lines = sum(len(c.line_hashes) for c in chunks)
    lines_by_tool = Counter()
    for c in chunks:
        lines_by_tool[c.tool] += len(c.line_hashes)

    return "\n".join([
        f"# AI PR Attribution — project overview",
        "",
        DASHBOARD_MARKER,
        f"_Last updated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}_",
        "",
        f"**{total_lines:,}** AI-attributed lines across **{len(chunks):,}** events.",
        "",
        _by_tool_section(lines_by_tool, total_lines),
        "",
        _trend_section(chunks),
        "",
        _top_files_section(chunks),
        "",
        _by_author_section(chunks),
        "",
        "---",
        "<sub>This page is auto-generated by the AI PR Attribution workflow. "
        "Hashes only — no source code is stored.</sub>",
        "",
    ])


def _empty() -> str:
    return "\n".join([
        "# AI PR Attribution — project overview",
        "",
        DASHBOARD_MARKER,
        "_No attribution events recorded yet._",
        "",
        "Once developers install the hooks and open a PR, stats will appear here.",
        "",
    ])


def _by_tool_section(lines_by_tool: Counter, total: int) -> str:
    rows = "\n".join(
        f"| {TOOL_LABELS.get(tool, tool)} | {count:,} | {count / total * 100:.0f}% |"
        for tool, count in sorted(lines_by_tool.items(), key=lambda kv: -kv[1])
    )
    pie_slices = "\n".join(
        f'    "{TOOL_LABELS.get(tool, tool)}" : {count}'
        for tool, count in sorted(lines_by_tool.items(), key=lambda kv: -kv[1])
    )
    return "\n".join([
        "## By tool",
        "",
        "| Tool | Lines | Share |",
        "|---|---:|---:|",
        rows,
        "",
        "```mermaid",
        "pie showData",
        '    title Lines by tool',
        pie_slices,
        "```",
    ])


def _trend_section(chunks: list[AiCodeChunk]) -> str:
    by_week: dict[str, int] = defaultdict(int)
    for c in chunks:
        week = _iso_week(c.event_time)
        if week:
            by_week[week] += len(c.line_hashes)

    if not by_week:
        return "## Trend\n\n_No timestamped events to plot._"

    weeks = sorted(by_week.items())[-12:]  # last 12 weeks
    x_axis = "[" + ", ".join(f'"{w}"' for w, _ in weeks) + "]"
    series = "[" + ", ".join(str(n) for _, n in weeks) + "]"

    return "\n".join([
        "## Trend — last 12 weeks",
        "",
        "```mermaid",
        "xychart-beta",
        '    title "AI-attributed lines per week"',
        f"    x-axis {x_axis}",
        '    y-axis "Lines"',
        f"    bar {series}",
        "```",
    ])


def _top_files_section(chunks: list[AiCodeChunk]) -> str:
    by_file: Counter[str] = Counter()
    for c in chunks:
        by_file[c.file_path] += len(c.line_hashes)
    rows = "\n".join(
        f"| `{path}` | {count:,} |"
        for path, count in by_file.most_common(10)
    ) or "| _none_ | 0 |"
    return "\n".join([
        "## Top files",
        "",
        "| File | AI lines |",
        "|---|---:|",
        rows,
    ])


def _by_author_section(chunks: list[AiCodeChunk]) -> str:
    by_author: Counter[str] = Counter()
    for c in chunks:
        author = c.metadata.get("user_hash") or c.metadata.get("author") or "unknown"
        by_author[author] += len(c.line_hashes)
    if len(by_author) <= 1 and "unknown" in by_author:
        return ""
    rows = "\n".join(
        f"| `{author}` | {count:,} |"
        for author, count in by_author.most_common(20)
    )
    return "\n".join([
        "## By contributor (anonymized hash)",
        "",
        "| Contributor | AI lines |",
        "|---|---:|",
        rows,
    ])


def _iso_week(event_time: str) -> str | None:
    if not event_time:
        return None
    try:
        ts = event_time.replace("Z", "+00:00")
        dt = datetime.fromisoformat(ts)
    except ValueError:
        return None
    year, week, _ = dt.isocalendar()
    return f"{year}-W{week:02d}"
