"""Render a project-wide AI usage dashboard as markdown.

Trend-focused, KPI-led, Metabase-style. Output is a single self-contained
.md file with native GitHub-rendered Mermaid charts.
"""
from __future__ import annotations

import subprocess
from collections import Counter, defaultdict
from datetime import datetime, timedelta, timezone
from pathlib import Path

from ai_use.events import read_chunks
from ai_use.schema import AiCodeChunk

TOOL_LABELS = {"claude_code": "Claude Code", "cursor": "Cursor", "codex": "Codex"}
DASHBOARD_MARKER = "<!-- ai-use:dashboard -->"
WEEKS = 12


def render_dashboard_markdown(events_file: Path, repo: Path | None = None) -> str:
    chunks = read_chunks(events_file)
    if not chunks:
        return _empty()

    weeks = _last_n_weeks(WEEKS)
    ai_by_week = _ai_lines_by_week(chunks, weeks)
    ai_by_tool_week = _ai_lines_by_tool_week(chunks, weeks)
    total_by_week = _total_lines_by_week(repo, weeks) if repo else {w: 0 for w in weeks}

    pct_by_week = _percent_by_week(ai_by_week, total_by_week)
    kpis = _kpis(ai_by_week, total_by_week, pct_by_week, chunks)

    return "\n".join([
        "# AI Usage",
        "",
        DASHBOARD_MARKER,
        f"_Last updated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}_",
        "",
        _kpi_cards(kpis),
        "",
        _pct_trend_section(weeks, pct_by_week),
        "",
        _tool_trend_section(weeks, ai_by_tool_week),
        "",
        _current_tool_split_section(ai_by_tool_week, weeks[-1]),
        "",
        "---",
        "<sub>Auto-generated by AI PR Attribution. Hashes only — no source code is stored.</sub>",
        "",
    ])


# ── KPIs ──────────────────────────────────────────────────────────────────────

def _kpis(ai_by_week, total_by_week, pct_by_week, chunks):
    weeks = list(ai_by_week.keys())
    this_week, last_week = weeks[-1], weeks[-2] if len(weeks) >= 2 else weeks[-1]

    this_pct = pct_by_week.get(this_week, 0)
    last_pct = pct_by_week.get(last_week, 0)
    delta = this_pct - last_pct

    active_tools = {c.tool for c in chunks if c.event_time and _week_of(c.event_time) == this_week}

    return {
        "this_pct": this_pct,
        "delta": delta,
        "this_ai": ai_by_week.get(this_week, 0),
        "this_total": total_by_week.get(this_week, 0),
        "active_tools": sorted(active_tools),
        "total_ai_12w": sum(ai_by_week.values()),
    }


def _kpi_cards(kpi: dict) -> str:
    arrow = "↑" if kpi["delta"] > 0 else ("↓" if kpi["delta"] < 0 else "→")
    delta_str = f"{arrow} {abs(kpi['delta']):.0f} pts vs last week"
    tools = ", ".join(TOOL_LABELS.get(t, t) for t in kpi["active_tools"]) or "—"
    return "\n".join([
        "## At a glance",
        "",
        "| | |",
        "|---|---|",
        f"| **AI share this week** | **{kpi['this_pct']:.0f}%** &nbsp; <sub>{delta_str}</sub> |",
        f"| **AI lines this week** | {kpi['this_ai']:,} of {kpi['this_total']:,} added |",
        f"| **AI lines last 12 weeks** | {kpi['total_ai_12w']:,} |",
        f"| **Active tools this week** | {tools} |",
    ])


# ── trend charts ──────────────────────────────────────────────────────────────

def _pct_trend_section(weeks: list[str], pct_by_week: dict) -> str:
    x = "[" + ", ".join(f'"{w[5:]}"' for w in weeks) + "]"  # short label (W##)
    y = "[" + ", ".join(f"{pct_by_week.get(w, 0):.0f}" for w in weeks) + "]"
    return "\n".join([
        "## AI share over time",
        "",
        "```mermaid",
        "xychart-beta",
        '    title "% of new lines attributed to AI"',
        f"    x-axis {x}",
        '    y-axis "%" 0 --> 100',
        f"    line {y}",
        "```",
    ])


def _tool_trend_section(weeks: list[str], ai_by_tool_week: dict) -> str:
    x = "[" + ", ".join(f'"{w[5:]}"' for w in weeks) + "]"
    # one chart per tool to keep Mermaid happy (multi-line legends are flaky)
    charts = []
    for tool in sorted(TOOL_LABELS):
        series = ai_by_tool_week.get(tool, {})
        if not any(series.get(w) for w in weeks):
            continue
        y = "[" + ", ".join(str(series.get(w, 0)) for w in weeks) + "]"
        charts.append("\n".join([
            f"### {TOOL_LABELS[tool]}",
            "",
            "```mermaid",
            "xychart-beta",
            f'    title "{TOOL_LABELS[tool]} — AI lines per week"',
            f"    x-axis {x}",
            '    y-axis "Lines"',
            f"    bar {y}",
            "```",
        ]))
    if not charts:
        return ""
    return "## By tool over time\n\n" + "\n\n".join(charts)


def _current_tool_split_section(ai_by_tool_week: dict, week: str) -> str:
    current = {tool: series.get(week, 0) for tool, series in ai_by_tool_week.items()}
    total = sum(current.values())
    if total == 0:
        return ""
    rows = "\n".join(
        f"| {TOOL_LABELS.get(tool, tool)} | {count:,} | {count / total * 100:.0f}% |"
        for tool, count in sorted(current.items(), key=lambda kv: -kv[1]) if count > 0
    )
    return "\n".join([
        "## This week by tool",
        "",
        "| Tool | Lines | Share |",
        "|---|---:|---:|",
        rows,
    ])


# ── data aggregation ──────────────────────────────────────────────────────────

def _last_n_weeks(n: int) -> list[str]:
    today = datetime.now(timezone.utc).date()
    # ISO week of today, walk back n-1 weeks
    weeks = []
    for offset in range(n - 1, -1, -1):
        d = today - timedelta(weeks=offset)
        year, week, _ = d.isocalendar()
        weeks.append(f"{year}-W{week:02d}")
    return weeks


def _ai_lines_by_week(chunks: list[AiCodeChunk], weeks: list[str]) -> dict[str, int]:
    bucket: dict[str, int] = {w: 0 for w in weeks}
    for c in chunks:
        w = _week_of(c.event_time)
        if w in bucket:
            bucket[w] += len(c.line_hashes)
    return bucket


def _ai_lines_by_tool_week(chunks: list[AiCodeChunk], weeks: list[str]):
    bucket: dict[str, dict[str, int]] = defaultdict(lambda: {w: 0 for w in weeks})
    for c in chunks:
        w = _week_of(c.event_time)
        if w in bucket[c.tool] or w in weeks:
            bucket[c.tool][w] = bucket[c.tool].get(w, 0) + len(c.line_hashes)
    return dict(bucket)


def _total_lines_by_week(repo: Path, weeks: list[str]) -> dict[str, int]:
    """Use git log --numstat to count added lines per week."""
    bucket = {w: 0 for w in weeks}
    earliest = weeks[0]
    since_date = _iso_week_start(earliest).isoformat()
    try:
        result = subprocess.run(
            ["git", "log", f"--since={since_date}", "--no-merges",
             "--pretty=format:COMMIT %ai", "--numstat"],
            cwd=repo, capture_output=True, text=True, check=True,
        )
    except (FileNotFoundError, subprocess.CalledProcessError):
        return bucket

    current_week: str | None = None
    for line in result.stdout.splitlines():
        if line.startswith("COMMIT "):
            current_week = _week_of(line[len("COMMIT "):])
            continue
        if not line.strip() or current_week not in bucket:
            continue
        parts = line.split("\t")
        if len(parts) < 3:
            continue
        added = parts[0]
        if added == "-":  # binary file
            continue
        try:
            bucket[current_week] += int(added)
        except ValueError:
            continue
    return bucket


def _percent_by_week(ai: dict, total: dict) -> dict[str, float]:
    pct = {}
    for w in ai:
        t = total.get(w, 0)
        pct[w] = (ai[w] / t * 100) if t > 0 else 0.0
        if pct[w] > 100:  # ai hooks can exceed git's added count (rewrites, etc.)
            pct[w] = 100
    return pct


def _week_of(event_time: str) -> str | None:
    if not event_time:
        return None
    try:
        ts = event_time.replace("Z", "+00:00")
        dt = datetime.fromisoformat(ts)
    except ValueError:
        return None
    year, week, _ = dt.isocalendar()
    return f"{year}-W{week:02d}"


def _iso_week_start(week_label: str):
    year, week = week_label.split("-W")
    return datetime.fromisocalendar(int(year), int(week), 1).date()


def _empty() -> str:
    return "\n".join([
        "# AI Usage",
        "",
        DASHBOARD_MARKER,
        "_No attribution events recorded yet._",
        "",
        "Once developers install the hooks and open PRs, trends will appear here.",
        "",
    ])
